### ISSUE TITLE
add cool animation on initial load

### ISSUE THREAD

**Issue by dannydeezy** [cold-sats/tao-web#3]
pm me for the files we have for animations

**Comment by cold-sats** [comment]
I added the animation but the mp4 has a lot of black space around it so I zoomed which made it a bit blurry. Any chance you can get an mp4 with no black space around the animation?

The original mp4:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/39313620/195976551-cd151ffd-ef29-4b4a-baa4-4b4b9eb3d391.png">

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/39313620/195976596-a04c9ec8-f054-430e-b6c2-1fec95583f03.png">

Also this is nitpicky but the diamond isn't aligned under the A if we can fix. It's a bit noticeable when you've watched this animation 100 times now on the landing page. Great animation though:

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/39313620/195976632-216aae94-d270-4e74-9594-46165e29cfbf.png">

**Comment by cold-sats** [comment]
Added in commit https://github.com/cold-sats/tao-web/commit/170ca4867e2207ac17a0823c789f7e597e8c600f
