### ISSUE TITLE
should use tao-wallet npm package

### ISSUE THREAD

**Issue by dannydeezy** [cold-sats/tao-web#5]
ideally this would use the [tao-wallet npm package](https://www.npmjs.com/package/tao-wallet) so we can separate UI logic from library logic

however i think `tao-wallet`, might not be usable in browser yet

**Comment by cold-sats** [comment]
Added in commit: https://github.com/cold-sats/tao-web/commit/feefd97781cd76da8f8c6ccca664fa9a441f5b98
